export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const EDIT_USER_REQUEST = "EDIT_USER_REQUEST";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_FAILURE = "EDIT_USER_FAILURE";


export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const SEARCH_USER_REQUEST = "SEARCH_USER_REQUEST";
export const SEARCH_USER_SUCCESS = "SEARCH_USER_SUCCESS";
export const SEARCH_USER_FAILURE = "SEARCH_USER_FAILURE";


//POST
export const GET_POST_REQUEST = "GET_POST_REQUEST";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";
export const GET_POST_FAILURE = "GET_POST_FAILURE";

export const GET_FRIENDS_POST_REQUEST = "GET_FRIENDS_POST_REQUEST";
export const GET_FRIENDS_POST_SUCCESS = "GET_FRIENDS_POST_SUCCESS";
export const GET_FRIENDS_POST_FAILURE = "GET_FRIENDS_POST_FAILURE";

export const UPLOAD_POST_REQUEST = "UPLOAD_POST_REQUEST";
export const UPLOAD_POST_SUCCESS = "UPLOAD_POST_SUCCESS";
export const UPLOAD_POST_FAILURE = "UPLOAD_POST_FAILURE";

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAILURE = "DELETE_POST_FAILURE";

export const UPDATE_POST_REQUEST = "UPDATE_POST_REQUEST";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const UPDATE_POST_FAILURE = "UPDATE_POST_FAILURE";

export const GET_POST_BY_ID_REQUEST = "GET_POST_BY_ID_REQUEST";
export const GET_POST_BY_ID_SUCCESS = "GET_POST_BY_ID_SUCCESS";
export const GET_POST_BY_ID_FAILURE = "GET_POST_BY_ID_FAILURE";


//COMMENT
export const ADD_COMMENT_REQUEST = "ADD_COMMENT_REQUEST";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAILURE = "ADD_COMMENT_FAILURE";

export const EDIT_COMMENT_REQUEST = "EDIT_COMMENT_REQUEST";
export const EDIT_COMMENT_SUCCESS = "EDIT_COMMENT_SUCCESS";
export const EDIT_COMMENT_FAILURE = "EDIT_COMMENT_FAILURE";

export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAILURE = "DELETE_COMMENT_FAILURE";


//LIKE
export const LIKE_REQUEST = "LIKE_REQUEST";
export const LIKE_SUCCESS = "LIKE_SUCCESS";
export const LIKE_FAILURE = "LIKE_FAILURE";

export const DISLIKE_REQUEST = "DISLIKE_REQUEST";
export const DISLIKE_SUCCESS = "DISLIKE_SUCCESS";
export const DISLIKE_FAILURE = "DISLIKE_FAILURE";


//FRIENDS
export const SEND_FRIEND_REQUEST = "SEND_FRIEND_REQUEST";
export const SEND_FRIEND_SUCCESS = "SEND_FRIEND_SUCCESS";
export const SEND_FRIEND_FAILURE = "SEND_FRIEND_FAILURE";

export const GET_REQUEST_LIST_REQUEST = "GET_REQUEST_LIST_REQUEST";
export const GET_REQUEST_LIST_SUCCESS = "GET_REQUEST_LIST_SUCCESS";
export const GET_REQUEST_LIST_FAILURE = "GET_REQUEST_LIST_FAILURE";

export const GET_REQUEST_SENT_LIST_REQUEST = "GET_REQUEST_SENT_LIST_REQUEST";
export const GET_REQUEST_SENT_LIST_SUCCESS = "GET_REQUEST_SENT_LIST_SUCCESS";
export const GET_REQUEST_SENT_LIST_FAILURE = "GET_REQUEST_SENT_LIST_FAILURE";

export const GET_FRIENDS_LIST_REQUEST = "GET_FRIENDS_LIST_REQUEST";
export const GET_FRIENDS_LIST_SUCCESS = "GET_FRIENDS_LIST_SUCCESS";
export const GET_FRIENDS_LIST_FAILURE = "GET_FRIENDS_LIST_FAILURE";

export const ACCEPT_FRIEND_REQUEST_REQUEST = "ACCEPT_FRIEND_REQUEST_REQUEST";
export const ACCEPT_FRIEND_REQUEST_SUCCESS = "ACCEPT_FRIEND_REQUEST_SUCCESS";
export const ACCEPT_FRIEND_REQUEST_FAILURE = "ACCEPT_FRIEND_REQUEST_FAILURE";

export const REJECT_FRIEND_REQUEST_REQUEST = "REJECT_FRIEND_REQUEST_REQUEST";
export const REJECT_FRIEND_REQUEST_SUCCESS = "REJECT_FRIEND_REQUEST_SUCCESS";
export const REJECT_FRIEND_REQUEST_FAILURE = "REJECT_FRIEND_REQUEST_FAILURE";

export const REMOVE_FRIEND_REQUEST_REQUEST = "REMOVE_FRIEND_REQUEST_REQUEST";
export const REMOVE_FRIEND_REQUEST_SUCCESS = "REMOVE_FRIEND_REQUEST_SUCCESS";
export const REMOVE_FRIEND_REQUEST_FAILURE = "REMOVE_FRIEND_REQUEST_FAILURE";

export const REMOVE_FRIEND_REQUEST = "REMOVE_FRIEND_REQUEST";
export const REMOVE_FRIEND_SUCCESS = "REMOVE_FRIEND_SUCCESS";
export const REMOVE_FRIEND_FAILURE = "REMOVE_FRIEND_FAILURE";


export const AUTH_USER = "AUTH_USER";
export const AUTH_USER_FAILURE = "AUTH_USER_FAILURE"

//Conversation

export const GET_CONVERSATION_REQUEST = "GET_CONVERSATION_REQUEST"
export const GET_CONVERSATION_SUCCESS = "GET_CONVERSATION_SUCCESS"
export const GET_CONVERSATION_FAILURE = "GET_CONVERSATION_FAILURE"

export const CREATE_CONVERSATION_REQUEST = "CREATE_CONVERSATION_REQUEST"
export const CREATE_CONVERSATION_SUCCESS = "CREATE_CONVERSATION_SUCCESS"
export const CREATE_CONVERSATION_FAILURE = "CREATE_CONVERSATION_FAILURE"

//Message

export const CREATE_MESSAGE_REQUEST = "CREATE_MESSAGE_REQUEST"
export const CREATE_MESSAGE_SUCCESS = "CREATE_MESSAGE_SUCCESS"
export const CREATE_MESSAGE_FAILURE = "CREATE_MESSAGE_FAILURE"


export const GET_MESSAGE_REQUEST = "GET_MESSAGE_REQUEST"
export const GET_MESSAGE_SUCCESS = "GET_MESSAGE_SUCCESS"
export const GET_MESSAGE_FAILURE = "GET_MESSAGE_FAILURE"

export const ADD_ARRIVAL_MESSAGE = "ADD_ARRIVAL_MESSAGE"


export const ADD_ONLINE_USER = "ADD_ONLINE_USER"